### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by sfkaos** [HarrisRobin/medium-scraper#2]
I'm getting this when running `node index.js`

```
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/win/Development/medium-scraper/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at null.<anonymous> (/Users/win/Development/medium-scraper/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/win/Development/medium-scraper/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1238:8)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
```

**Comment by HarrisRobin** [comment]
@sfkaos i just updated mongoose to a newer version which should fix that issue.

1. pull my latest change
2. delete your node_modules
3. run npm install again


All this is assuming you have mongodb on your system.
Once you run `node index.js`, on your browser go to localhost:8080

That should work, just tested it.
